name: earthdaily
channels:
 - conda-forge
 - defaults
dependencies:
- numpy
- matplotlib<3.9
- joblib
- gdal
- scipy
- psutil
- flox
- pystac-client>=0.7
- pystac>=1.12.1
- odc-stac
- pandas>=2
- geopandas>=1
- requests
- xarray>=2024.7.0
- rasterio
- rioxarray
- tqdm
- python-dotenv
- rich
- dask>=2024.4
- spyndex
- dask-image>=2024
- toml
- click
- urllib3