name: earthdaily
channels:
 - conda-forge
 - defaults
dependencies:
- numpy
- matplotlib
- joblib
- scipy
- psutil
- pystac-client
- pystac
- odc-stac<=0.3.9
- pandas>=2
- geopandas
- requests
- xarray
- rasterio
- rioxarray
- tqdm
- python-dotenv
- rich
- dask>=2024.4
- spyndex
- dask-image
- toml
- click