name: earthdaily
channels:
 - conda-forge
 - defaults
dependencies:
- numpy
- matplotlib<3.9
- joblib
- gdal
- scipy
- psutil
- pystac-client
- pystac
- odc-stac
- pandas>=2
- geopandas>=1
- requests
- xarray>=2024.7.0
- rasterio
- rioxarray
- tqdm
- python-dotenv
- rich
- dask>=2024.4
- spyndex
- dask-image
- toml
- click
- urllib3