name: Lint, Format and Type Check

on:
  push:
    branches:
      - main
      - beta/*
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ${{ github.repository_visibility == 'private' && 'ed-runner-set' || 'ubuntu-latest' }}
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    container:
      image: python:${{ matrix.python-version }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y gdal-bin libgdal-dev

      - name: Install Poetry
        run: pip install poetry

      - name: Install test dependencies
        run: poetry install --only tests

      - name: Run Linting
        run: poetry run tox -e lint

      - name: Run Formatting Check
        run: poetry run tox -e format