name: lint-format-type-check

on:
  push:
    branches:
      - '**'

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install "ruff>=0.9.6,<1.0.0" "mypy>=1.0.0,<2.0.0" "types-tqdm>=4.67,<5.0.0"

      - name: Run Ruff Check
        run: ruff check . --select I

      - name: Run Ruff Format
        run: ruff format --check .

      - name: Run MyPy
        run: mypy .